logging:
  level:
    org.hibernate: ERROR

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/class-management?verifyServerCertificate=false&useSSL=true
    username: root
    password: root
    platform: mysql
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  jackson:
    default-property-inclusion: non_absent
---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?verifyServerCertificate=false&useSSL=true
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    initialize: true